name: Build Quatrix

on:
  push:
    tags:
      - "*.*.*"

env:
  CARGO_TERM_COLOR: always
  ITCH_USERNAME: alumux
  ITCH_GAME_ID: quatrix
  RUST_TOOLCHAIN: 1.77

jobs:
  build:
    strategy:
      matrix:
        include:
          - channel: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - channel: windows
            os: windows-latest
            target: x86_64-pc-windows-msvc
          - channel: mac
            os: macOS-latest
            target: x86_64-apple-darwin
          - channel: mac
            os: macOS-latest
            target: aarch64-apple-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get Version from Tag
        uses: olegtarasov/get-tag@v2.1.2
        id: get_version
      - name: Checkout with LFS
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Install Linux Dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update; sudo apt-get install pkg-config libx11-dev libasound2-dev libudev-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev
      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          targets: ${{ matrix.target }}
      - name: Add Target
        run: rustup target add ${{ matrix.target }}
      - name: Set Environment On Mac ARM 
        if: matrix.target == 'aarch64-apple-darwin'
        # https://github.com/bevyengine/bevy_github_ci_template/blob/main/.github/workflows/release.yaml macOS 11 was the first version to support ARM
        run: |
          export MACOSX_DEPLOYMENT_TARGET="11"
      - name: Build Game
        run: cargo install --locked --root install --path . --target ${{ matrix.target }}
      - name: Copy In Assets
        uses: Lyoko-Jeremie/js-copy-github-action@master
        with:
          source: assets
          target: install/bin/assets
      - name: Publish to Itch.io
        uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{ secrets.BUTLER_API_KEY }}
          gameData: install/bin/
          itchUsername: ${{ env.ITCH_USERNAME }}
          itchGameId: ${{ env.ITCH_GAME_ID }}
          buildNumber: ${{ steps.get_version.outputs.tag }}
          buildChannel: ${{ matrix.channel }}
